### ISSUE TITLE
Vue 2 support?

### ISSUE THREAD

**Issue by aedart** [JeffreyWay/Laravel-Elixir-Rollup#10]
I have been trying to get Vue 2 to work with rollup, using this elixir extension. Unfortunately it does not appear to work that well.
## The problem

It appears that the `rollup-plugin-vue` cannot handle the Vue 2 's templates, due to the usage of `with` statements (assuming this is Vue 2 internal).
## Possible solution

Perhaps using this [plugin](https://github.com/thgh/rollup-plugin-vue2) could resolve the issue. But not too sure about the way they are doing it.

I did attempt to use this plugin locally, by using a `rollup.config.js`, yet gulp fails at the import statements (`import vue from 'rollup-plugin-vue2';`)... uh, ... Hope that you (or someone) can help.

**Comment by JeffreyWay** [comment]
Coming soon.

**Comment by aedart** [comment]
Ok - ty :)

**Comment by patricksamson** [comment]
Any news on this issue? `rollup-plugin-vue2` seems nice, but looks like it needs another plugin to bundle the CSS. I might try to implement it, but all these compilers and transpilers are difficult to debug!

**Comment by dzava** [comment]
Both plugins `rollup-plugin-vue` and `rollup-plugin-vue2` use `vue-template-compiler` which produces templates that use `with`, `rollup-plugin-vue2` works because it disables strict mode, which you can do in `rollup.config.js`

**Comment by zackkrida** [comment]
@dzava how does one disable strict mode within a `rollup.config.js` file? I can't find documentation on this anywhere.

Regardless, I'd love to see this working with Vue 2 single-file components.

**Comment by dzava** [comment]
@zackcote set [useStrict](https://github.com/rollup/rollup/wiki/JavaScript-API#usestrict) to false.

There is a template [compiler](https://github.com/vuejs/vue-template-es2015-compiler) that makes render functions compatible with strict mode and
[looks like](https://github.com/thgh/rollup-plugin-vue2/blob/master/src/vueTransform.js#L92) `rollup-plugin-vue2` can be used in strict mode.
