### ISSUE TITLE
Update call to rollup

### ISSUE THREAD

**Issue by mundomatt** [JeffreyWay/Laravel-Elixir-Rollup#19]
As of this rollup commit (https://github.com/rollup/rollup/pull/1566) the `moduleName` option was normalized to `name`, as well as `sourceMap` renamed to lowercase `sourcemap`. These changes need to be reflected in the rollup call in `RollupTask.js` line 104:

```
        return rollup(
            extend({
                entry: this.src.path,
                cache: cache,
                sourceMap: true,
                format: 'iife',
                moduleName: 'LaravelElixirBundle',
                plugins: plugins
            }, this.rollupConfig, this.options)
        )
        .on('bundle', function (bundle) {
            cache = bundle;
        });
```

**Comment by mbaierl** [comment]
Hey guys,
any chance to fix this? Open since September...

**Comment by pilishen** [comment]
Korko's commit was a right fix,
thanks
shame to mannually change source code
